// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrUpdateCustomerFromResponse(arg1) {
  return window['go']['repository']['Repository']['CreateOrUpdateCustomerFromResponse'](arg1);
}

export function CreateOrUpdateProductFromResponse(arg1) {
  return window['go']['repository']['Repository']['CreateOrUpdateProductFromResponse'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['repository']['Repository']['Login'](arg1, arg2);
}

export function ReloadBundleSetting() {
  return window['go']['repository']['Repository']['ReloadBundleSetting']();
}

export function Setup(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['Setup'](arg1, arg2, arg3);
}

export function SyncCustomer() {
  return window['go']['repository']['Repository']['SyncCustomer']();
}

export function SyncGet(arg1) {
  return window['go']['repository']['Repository']['SyncGet'](arg1);
}

export function SyncProduct(arg1) {
  return window['go']['repository']['Repository']['SyncProduct'](arg1);
}

export function SyncSetting() {
  return window['go']['repository']['Repository']['SyncSetting']();
}

export function SyncUser() {
  return window['go']['repository']['Repository']['SyncUser']();
}

export function UpdateOrCreateSettingFromResponse(arg1) {
  return window['go']['repository']['Repository']['UpdateOrCreateSettingFromResponse'](arg1);
}

export function UpdateOrCreateUserFromResponse(arg1) {
  return window['go']['repository']['Repository']['UpdateOrCreateUserFromResponse'](arg1);
}

export function UpdateOrCreateUserFromResponseAuth(arg1) {
  return window['go']['repository']['Repository']['UpdateOrCreateUserFromResponseAuth'](arg1);
}
