// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {repository} from '../models';
import {context} from '../models';
import {gorm} from '../models';
import {api} from '../models';

export function CreateOrUpdateProductFromResponse(arg1:response.Product):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<repository.User>;

export function Setup(arg1:context.Context,arg2:gorm.DB,arg3:api.Api):Promise<void>;

export function SyncGet(arg1:string):Promise<void>;

export function UpdateOrCreateUserFromResponse(arg1:response.Auth):Promise<void>;
