// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrUpdateProductFromResponse(arg1) {
  return window['go']['repository']['Repository']['CreateOrUpdateProductFromResponse'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['repository']['Repository']['Login'](arg1, arg2);
}

export function Setup(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['Setup'](arg1, arg2, arg3);
}

export function SyncGet(arg1) {
  return window['go']['repository']['Repository']['SyncGet'](arg1);
}

export function UpdateOrCreateUserFromResponse(arg1) {
  return window['go']['repository']['Repository']['UpdateOrCreateUserFromResponse'](arg1);
}
