// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBaseUrl() {
  return window['go']['main']['App']['GetBaseUrl']();
}

export function SetBaseUrl(arg1) {
  return window['go']['main']['App']['SetBaseUrl'](arg1);
}
