// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBaseUrl():Promise<string>;

export function SetBaseUrl(arg1:string):Promise<void>;
